// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrczdncygntrvkzjcqmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyY3pkbmN5Z250cnZrempjcW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMTIzOTMsImV4cCI6MjA1MTU4ODM5M30.B83-aIzoHQpJuOGoyULt-r6hoydHco1SNDYAo2rdYlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);